import QtQuick 2.5

Item {
    readonly property color ffWhite: "white"
    readonly property color ffBlack: "black"
    readonly property color ffRed: "red"
    readonly property color ffGreen: "#166427"
    readonly property color ffLightGreen: "#168827"
    readonly property color ffDarkGreen: "darkgreen"
    readonly property color ffBlue: "blue"
    readonly property color ffLightBlue: "lightblue"
    readonly property color ffSteelBlue: "steelblue"
    readonly property color ffGreenCompliment: "#56A166"
    readonly property color ffGreenTriad: "#271564"
    readonly property color ffCapsLock: "blue"
    readonly property color ffKeyLabel: ffGreen
    readonly property color ffKeyButton: ffGreenCompliment
    readonly property color ffPull: "red"
    readonly property color ffStock: "green"
    readonly property color ffPar: "black"
    readonly property color ffException: "blue"
    readonly property color ffOrange: "orange"
    readonly property color ffGray: "gray"
    readonly property color ffLightGray: "lightgray"
    readonly property color ffPink: "pink"
    readonly property color ffYellow: "yellow"
    readonly property color ffIvory: "ivory"
    readonly property color ffBrown: "brown"
    readonly property color ffLineColor: "#757365"
    readonly property color ffTransparent: "transparent"
    readonly property color ffGray1: "#888"
    readonly property color ffGray2: "#eee"
    readonly property color ffGray3: "#ccc"
    readonly property color ffToolBarSeparator1: "#22000000"
    readonly property color ffToolBarSeparator2: "#33ffffff"
    readonly property color ffKeyColor: "#34495E"
    readonly property color ffKeyPressedColor: "#1ABC9C"
    readonly property color ffKbdBkgColor: "#192430"
    readonly property color ffKeyLabelColor: "#F2F2F2"
}

