#ifndef FARMERSSERVER_GLOBAL_H
#define FARMERSSERVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FARMERSSERVER_LIBRARY)
#  define FARMERSSERVERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FARMERSSERVERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FARMERSSERVER_GLOBAL_H
