#ifndef FARMERSCLIENTVER_GLOBAL_H
#define FARMERSCLIENTVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FARMERSCLIENT_LIBRARY)
#  define FARMERSCLIENTVERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FARMERSCLIENTVERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FARMERSCLIENTVER_GLOBAL_H
